version: '3'

volumes:
  assemble_shop_local_postgres_data: {}
  assemble_shop_local_postgres_data_backups: {}
  assemble_shop_local_minio_data: {}


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: assemble_shop_local_django
    container_name: assemble_shop_local_django
    depends_on:
      - postgres
      - minio
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: assemble_shop_production_postgres
    container_name: assemble_shop_local_postgres
    volumes:
      - assemble_shop_local_postgres_data:/var/lib/postgresql/data
      - assemble_shop_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  minio:
    image: assemble_shop_local_minio
    container_name: assemble_shop_local_minio
    build:
      context: .
      dockerfile: ./compose/local/minio/Dockerfile
    volumes:
      - assemble_shop_local_minio_data:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    env_file:
      - ./.envs/.local/.minio
