# Generated by Django 5.0.9 on 2024-11-30 09:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Tracking Code'),
        ),
    ]
