# Generated by Django 5.0.9 on 2024-12-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_discount_updated_by_alter_order_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
