# Generated by Django 5.0.9 on 2024-12-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_by',
        ),
    ]
