# Generated by Django 5.0.9 on 2024-12-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_orderitem_created_at_orderitem_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount Percentage'),
        ),
    ]
